# Generated by Django 4.0.2 on 2022-02-08 14:27

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_roles(apps, schema_editor):
    User = apps.get_model('user', 'User')
    User.objects.create(
        username='dote',
        first_name='Jhon',
        last_name='Sanz',
        email='ssanzjhon5@gmail.com',
        password=make_password('Hola123...'),
        is_staff=True,
        is_superuser=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
