# Generated by Django 4.0.2 on 2022-02-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('order_date', models.DateField()),
                ('currency', models.CharField(max_length=10)),
                ('purchase_price', models.FloatField()),
                ('invested_amount_usd', models.FloatField()),
                ('invested_amount_cop', models.FloatField()),
                ('comission_convertion', models.FloatField()),
                ('comission_purchase_binance', models.FloatField()),
                ('type', models.CharField(choices=[(0, 'Sell'), (1, 'Buy')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
