# Generated by Django 4.0.2 on 2022-02-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Sell'), (1, 'Buy')]),
        ),
    ]
