# Generated by Django 4.0.2 on 2022-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comission_convertion',
            new_name='amount_currency',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='comission_purchase_binance',
            new_name='commission_conversion',
        ),
        migrations.AddField(
            model_name='order',
            name='commission_purchase_binance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
