# Generated by Django 4.0.2 on 2022-03-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_comission_convertion_order_amount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.order'),
        ),
    ]
